[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; --- 啟用 PSRAM 設定 ---
;board_build.arduino.memory_type = qio_opi  ; ESP32-S3 常見的 OPI PSRAM 配置
board_build.arduino.memory_type = qio_qspi  ; ESP32-S3 常見的 QSPI PSRAM 配置
build_flags = 
    -DBOARD_HAS_PSRAM

; 🔑 關鍵 16MB Flash 與分區表解鎖設定
board_upload.flash_size = 16MB
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.arduino.partitions = default_16MB.csv

lib_deps = 
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ILI9341 @ ^1.5.14


